<?xml version="1.0" encoding="utf-8"?><Database Name="QLNHANVIEN" Class="EmployeeDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLExpress;Initial Catalog=QLNHANVIEN;Integrated Security=True" SettingsObjectName="QLNHANVIENFULL.Properties.Settings" SettingsPropertyName="QLNHANVIENConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Account" Member="Accounts">
    <Type Name="Account">
      <Column Name="username" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Department" Member="Departments">
    <Type Name="Department">
      <Column Name="DepId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DepName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="Department_Employee" Member="Employees" ThisKey="DepId" OtherKey="EmpDep" Type="Employee" />
    </Type>
  </Table>
  <Table Name="dbo.Employee" Member="Employees">
    <Type Name="Employee">
      <Column Name="EmpID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmpName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="EmpGen" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="EmpDep" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EmpDOB" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="EmpJDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="EmpSal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EmpImage" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Association Name="Employee_Salary" Member="Salaries" ThisKey="EmpID" OtherKey="EmployeeID" Type="Salary" />
      <Association Name="Department_Employee" Member="Department" ThisKey="EmpDep" OtherKey="DepId" Type="Department" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Salary" Member="Salaries">
    <Type Name="Salary">
      <Column Name="Scode" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Period" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Salary" Member="Salary1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Paydate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="EmployeeName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[From]" Member="From" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="[To]" Member="To" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="totalsal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Employee_Salary" Member="Employee" ThisKey="EmployeeID" OtherKey="EmpID" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
</Database>